---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(tidycensus)
```


```{r}
vars_19 = load_variables(2019, "acs5", cache = TRUE)

vars_19_cleaned = vars_19 %>%
  mutate(label = snakecase::to_snake_case(label),
         concept = snakecase::to_snake_case(label))

vars_19_cleaned %>% write_rds(file.path("variables.rds"))
vars_19_cleaned %>% write_csv(file.path("variables.csv"))
```


```{r}
wayne_data = map_dfr(list(vars_19$name), function(.x) {get_acs(
  geography = "block group",
  variables =  .x,
  output = "tidy",
  state = "MI",
  county = "Wayne",
  year = 2019,
  geometry = TRUE,
  keep_geo_vars = TRUE)})

wayne_data %>% dim()
```

```{r}
wayne_data_w_labels = wayne_data %>%
  rename(Location = NAME) %>% 
  left_join(vars_19_cleaned, by = c("variable" = "name"))

wayne_data_w_labels %>% write_rds(file.path("wayne_data.rds"))
wayne_data_w_labels %>% write_csv(file.path("wayne_data.csv"))
```

# save shape data

```{r}
wayne_shape_data = get_acs(
  geography = "block group",
  variables =  "B01001_001",
  output = "tidy",
  state = "MI",
  county = "Wayne",
  year = 2019,
  geometry = TRUE,
  keep_geo_vars = TRUE)
wayne_shape_data %>% str()

wayne_shape_data %>% write_rds(file.path("wayne_shape_data.rds"))
wayne_shape_data %>% write_csv(file.path("wayne_shape_data.csv"))
```




