---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)

wayne_data_w_labels = read_rds("wayne_data.rds")

wayne_data_w_labels %>% head()

wayne_data_w_labels %>% dim()

wayne_data_w_labels %>% select(label) %>% unique() %>% nrow()
```
```{r}
library(jsonlite)
det_geoids = fromJSON("DetroitBlockGroupsPlusGeo.geojson", flatten=TRUE)
```


# Pivot wider

```{r}
wayne_data_wide = wayne_data_w_labels %>% 
  semi_join(det_geoids$features %>% select(GEOID = properties.GEOID10)) %>% 
  distinct(across(c(GEOID, Location, label)), .keep_all = TRUE) %>% 
  pivot_wider(id_cols = c("GEOID", "Location"), names_from = c("variable", "label"), values_from = "estimate") %>% 
  select_if(function(x) !(all(is.na(x)) | all(x=="")))

wayne_data_wide %>% 
  write_rds(file.path("wayne_data_wide.rds"))

wayne_data_wide %>% 
  write_csv(file.path("wayne_data_wide.csv"))

wayne_data_wide %>% dim()
```

# capture outcome labels

```{r}
wayne_data_wide %>% 
  select(contains("high_school")) #%>% 
  # names()
```


```{r}
computer_outcomes = wayne_data_wide %>% 
  select(ends_with("no_computer"), 
         contains("has_a_computer"), 
         contains("has_one_or_more_types_of_computing_devices")) %>% 
  names()

internet_outcomes = wayne_data_wide %>% 
  select(contains("no_internet_access"), 
         contains("with_an_internet_subscription"),
         contains("with_a_broadband_internet_subscription"),
         contains("without_an_internet_subscription")) %>% 
  names()
```

# Build outcomes

Build binary outcome for block groups one SD above the median for both no internet and no computer variables

```{r}
wayne_data_prepped = wayne_data_wide %>% 
  mutate(pct_no_computer = (estimate_total_no_computer / estimate_total) %>% round(2)) %>% 
  mutate(outcome_no_computer = if_else(pct_no_computer > (median(pct_no_computer, na.rm = TRUE) + sd(pct_no_computer, na.rm = TRUE)), 1, 0, 0) %>% as.factor()) %>% 
  mutate(pct_no_internet = (estimate_total_no_internet_access / estimate_total) %>% round(2)) %>% 
  mutate(outcome_no_internet = if_else(pct_no_internet > (median(pct_no_internet, na.rm = TRUE) + sd(pct_no_internet, na.rm = TRUE)), 1, 0, 0) %>% as.factor()) %>% 
  select(-c(pct_no_computer, pct_no_internet))

wayne_data_prepped %>% dim()

wayne_data_prepped %>% write_rds(file.path("wayne_data_prepped.rds"))
```


