---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(h2o)
library(runway)
h2o.init(nthreads=-1) # multiprocessing support
```

```{r eval=FALSE}
wayne_data_prepped = read_rds(file.path("wayne_data_prepped.rds"))
gbm_pc_model = h2o.loadModel(file.path("GBM_model_R_1640656019954_14307"))
gbm_net_model = h2o.loadModel(file.path("GBM_model_R_1640656019954_15277"))
folds = read_csv(file.path("folds.csv"))
```

```{r}
test_data = wayne_data_prepped %>% left_join(folds %>% mutate(GEOID = GEOID %>% as.character()) %>% filter(fold == 6))
```

# Test data predictions

```{r}
gbm_pc_model_predictions = gbm_pc_model %>%
  h2o.predict(test_data %>% as.h2o()) %>%
  as.data.frame() %>% 
  cbind(test_data %>% select(GEOID, outcome_no_computer)) %>% 
  mutate(outcome = outcome_no_computer %>% as.character() %>% as.numeric()) %>% 
  mutate(model = "No PC")

gbm_net_model_predictions = gbm_net_model %>%
  h2o.predict(test_data %>% as.h2o()) %>%
  as.data.frame() %>% 
  cbind(test_data %>% select(GEOID, outcome_no_internet)) %>% 
  mutate(outcome = outcome_no_internet %>% as.character() %>% as.numeric()) %>% 
  mutate(model = "No Internet")

all_predictions = bind_rows(gbm_pc_model_predictions, gbm_net_model_predictions) %>% 
  select(GEOID, model, outcome, p1)
```

# no PC model AUC

```{r}
gbm_pc_model_predictions %>%
  pROC::roc(outcome, p1, ci = TRUE, ci.method="bootstrap")
```

# No internet model AUC

```{r}
gbm_net_model_predictions %>%
  pROC::roc(outcome, p1, ci = TRUE, ci.method="bootstrap")
```

# Calibration plot

```{r}
runway::cal_plot_multi(all_predictions,
         outcome = "outcome",
         prediction = "p1",
         model = "model",
         n_bins = 0,
         show_loess = TRUE)

ggsave(file = "calibration_plot.png", width = 10, height = 10, units = 'in', dpi = 300, scale = 1)
```

# Threshold performance

```{r}
runway::threshperf_plot_multi(all_predictions,
         outcome = "outcome",
         model = "model",
         prediction = "p1")

ggsave(file = "threshold_performance.png", width = 10, height = 5, units = 'in', dpi = 300, scale = 1)
```

# Decision Curve Analysis

```{r}
gbm.pc.model = rmda::decision_curve(outcome~p1,
                            data = gbm_pc_model_predictions,
                            fitted.risk = TRUE,
                            thresholds = seq(0, .4, by = .05),
                            bootstraps = 25)

gbm.net.model = rmda::decision_curve(outcome~p1,
                            data = gbm_net_model_predictions,
                            fitted.risk = TRUE,
                            thresholds = seq(0, .4, by = .05),
                            bootstraps = 25)

rmda::plot_decision_curve(list(gbm.pc.model, gbm.net.model),
                    curve.names = c("PC Model", "Net Model"),
                    legend.position = "topright",
                    standardize = FALSE,
                    confidence.intervals = FALSE)
```


```{r}
runway::roc_plot_multi(all_predictions,
                 outcome = "outcome",
                 model = "model",
                 prediction = "p1",
                 ci = TRUE)

ggsave(file = "roc_plot_pred.png", width = 10, height = 10, units = 'in', dpi = 300, scale = 1)
```

```{r}
gbm_imp_pc = h2o.varimp(gbm_pc_model) %>%
  arrange(relative_importance) %>% 
  rename(pc_relative_importance = relative_importance, pc_scaled_importance = scaled_importance, pc_percentage = percentage)

gbm_imp_pc %>%
  as.data.frame() %>%
  head(20) %>%
  mutate(pc_relative_importance = pc_relative_importance %>% round(2)) %>%
  select(variable, pc_relative_importance) %>%
  arrange(desc(pc_relative_importance)) %>%
  ggplot(aes(x = reorder(variable, pc_relative_importance), y = pc_relative_importance)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("")
```

```{r}
gbm_imp_net = h2o.varimp(gbm_net_model) %>%
  arrange(desc(percentage)) %>% 
  rename(net_relative_importance = relative_importance, net_scaled_importance = scaled_importance, net_percentage = percentage)
```

```{r}
vars = read_rds(file.path("variables.rds"))

gbm_imp_all = bind_cols(vars %>% left_join(gbm_imp_net %>% as.data.frame(), by = c("label" = "variable")), 
                        vars %>% left_join(gbm_imp_pc %>% as.data.frame(), by = c("label" = "variable")) %>% select(-c(name, label, concept))) %>% 
  filter(!is.na(net_relative_importance) & !is.na(pc_relative_importance)) %>% 
  mutate(across(4:9, round, 1)) %>% 
  arrange(desc(net_scaled_importance))

gbm_imp_net %>%
  as.data.frame() %>%
  head(20) %>%
  mutate(net_scaled_importance = net_scaled_importance %>% round(2)) %>%
  select(variable, net_scaled_importance) %>%
  arrange(desc(net_scaled_importance)) %>%
  ggplot(aes(x = reorder(variable, net_scaled_importance), y = net_scaled_importance)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("")

ggsave(file = "variable_imp_plot.png", width = 10, height = 10, units = 'in', dpi = 300, scale = 1)

gbm_imp_all %>%
  as.data.frame() %>%
  write_csv(file.path("gbm_importance.csv"), append = FALSE)
```

```{r}
wayne_data_prepped %>%
  select(gbm_imp_net %>% slice(1:10) %>% pull(variable)) %>% 
  rename_all(.,~ stringr::str_sub(., 10L, 60L)) %>% 
  stats::cor(use = "pairwise.complete.obs") %>% 
  corrplot::corrplot(type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.8, tl.col = 'black',
         order = "hclust", diag = FALSE)
``` 
```{r}
wayne_data_prepped %>%
  select(gbm_imp_pc %>% slice(1:10) %>% pull(variable)) %>% 
  rename_all(.,~ stringr::str_sub(., 10L, 60L)) %>% 
  stats::cor(use = "pairwise.complete.obs") %>% 
  corrplot::corrplot(type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.8, tl.col = 'black',
         order = "hclust", diag = FALSE)
``` 


```{r eval=FALSE, include=FALSE}
h2o.shutdown(prompt=FALSE)
```